apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: green          # <--- Etiqueta de versión
  template:
    metadata:
      labels:
        app: webapp
        version: green       # <--- Etiqueta de versión
    spec:
      containers:
      - name: web
        image: app:v2    # Tu imagen original
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 3000   # Asegúrate de que sea el puerto de tu app
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080  # Asegúrate de que sea el puerto de tu app
          initialDelaySeconds: 5
          periodSeconds: 10