apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: blue          # <--- Etiqueta de versión
  template:
    metadata:
      labels:
        app: webapp
        version: blue        # <--- Etiqueta de versión
    spec:
      containers:
      - name: web
        image: app:latest    # Tu imagen original
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 3000   # Asegúrate de que sea el puerto de tu app
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080  # Asegúrate de que sea el puerto de tu app
          initialDelaySeconds: 5
          periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webapp
    version: blue
  ports:
    - port: 80
      targetPort: 8080
